/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SONY INDIA
 */
public class HotelMenuSystem extends javax.swing.JFrame {
    double IndianRupee=56.01;
    double Aud=1.8;
    double BritishPounds=0.59;
    double USD=0.76;
    double kenyanShilling=77.30;
    double NigerianNaira=277.70;
    double IndonesianRupiah=11598.12;
    
    double firstnum;
    double secondnum;
    double result;
    String Operations;

    /**
     * Creates new form HotelMenuSystem
     */
    public HotelMenuSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jVegBurgerCheckBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jVegBurgerTextField = new javax.swing.JTextField();
        jChickenBurgerCheckBox = new javax.swing.JCheckBox();
        jChickenBurgerTextField = new javax.swing.JTextField();
        jBaconCheckBox = new javax.swing.JCheckBox();
        jBaconTextField = new javax.swing.JTextField();
        jDrinkComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTaxCheckBox = new javax.swing.JCheckBox();
        jCheckBoxHomeDelivery = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jCostOfHomeDelivery = new javax.swing.JTextField();
        jCostOfDrinks = new javax.swing.JTextField();
        jCostOfMeal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCurrencyComboBox = new javax.swing.JComboBox<>();
        jCurrencyTextField = new javax.swing.JTextField();
        jCurrencyLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCurrencyConvert = new javax.swing.JButton();
        jCurrencyClose = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTotalTextField = new javax.swing.JTextField();
        jTaxTextField = new javax.swing.JTextField();
        jSubtotalTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtArea = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jtxtCalDisplay = new javax.swing.JTextField();
        jBtn1 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtnDecimal = new javax.swing.JButton();
        jBtnOpposite = new javax.swing.JButton();
        jBtnAdd = new javax.swing.JButton();
        jBtnSubtract = new javax.swing.JButton();
        jBtnMul = new javax.swing.JButton();
        jBtnDivide = new javax.swing.JButton();
        jBtnPercent = new javax.swing.JButton();
        jBtnClear = new javax.swing.JButton();
        jBtnBackspace = new javax.swing.JButton();
        jBtnEqualto = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jTotalBtn = new javax.swing.JButton();
        jReceiptBtn = new javax.swing.JButton();
        jResetbtn = new javax.swing.JButton();
        jExitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Restaurant Management Systems");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jVegBurgerCheckBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jVegBurgerCheckBox.setText("Veg. Burger");
        jVegBurgerCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVegBurgerCheckBoxMouseClicked(evt);
            }
        });
        jVegBurgerCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVegBurgerCheckBoxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Enter quantity");

        jVegBurgerTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jVegBurgerTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jVegBurgerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVegBurgerTextFieldActionPerformed(evt);
            }
        });

        jChickenBurgerCheckBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChickenBurgerCheckBox.setText("Chicken Burger");
        jChickenBurgerCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChickenBurgerCheckBoxMouseClicked(evt);
            }
        });

        jChickenBurgerTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChickenBurgerTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jChickenBurgerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChickenBurgerTextFieldActionPerformed(evt);
            }
        });

        jBaconCheckBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBaconCheckBox.setText("Bacon Chicken Burger");
        jBaconCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBaconCheckBoxMouseClicked(evt);
            }
        });
        jBaconCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBaconCheckBoxActionPerformed(evt);
            }
        });

        jBaconTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBaconTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jDrinkComboBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jDrinkComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a drink...", "Apple Juice", "Orange Juice", "Tea", "Hot Coffee", "Cold Coffee", "Coke", "Sprite" }));
        jDrinkComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDrinkComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Drinks");

        jTaxCheckBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTaxCheckBox.setText("Tax");
        jTaxCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTaxCheckBoxMouseClicked(evt);
            }
        });
        jTaxCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTaxCheckBoxActionPerformed(evt);
            }
        });

        jCheckBoxHomeDelivery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCheckBoxHomeDelivery.setText("Home Delivery");
        jCheckBoxHomeDelivery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxHomeDeliveryMouseClicked(evt);
            }
        });
        jCheckBoxHomeDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHomeDeliveryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jBaconCheckBox)
                            .addGap(18, 18, 18)
                            .addComponent(jBaconTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTaxCheckBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBoxHomeDelivery))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDrinkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jVegBurgerCheckBox)
                                .addComponent(jChickenBurgerCheckBox))
                            .addGap(80, 80, 80)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jChickenBurgerTextField)
                                .addComponent(jVegBurgerTextField))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 225, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jVegBurgerCheckBox)
                    .addComponent(jVegBurgerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChickenBurgerCheckBox)
                    .addComponent(jChickenBurgerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBaconCheckBox)
                    .addComponent(jBaconTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDrinkComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTaxCheckBox)
                    .addComponent(jCheckBoxHomeDelivery))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jCostOfHomeDelivery.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCostOfHomeDelivery.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jCostOfHomeDelivery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCostOfHomeDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCostOfHomeDeliveryActionPerformed(evt);
            }
        });

        jCostOfDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCostOfDrinks.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jCostOfDrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCostOfDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCostOfDrinksActionPerformed(evt);
            }
        });

        jCostOfMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCostOfMeal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jCostOfMeal.setText("0");
        jCostOfMeal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cost of Meal");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Cost of Drinks");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Cost of Home Delivery");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jCostOfDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jCostOfMeal)
                    .addComponent(jCostOfHomeDelivery))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jCostOfMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCostOfDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCostOfHomeDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jCurrencyComboBox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCurrencyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose one...", "India", "Australia", "England", "USA", "Kenya", "Indonesia", "Nigeria" }));

        jCurrencyTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCurrencyTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jCurrencyTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jCurrencyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCurrencyTextFieldActionPerformed(evt);
            }
        });

        jCurrencyLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCurrencyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCurrencyLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("CAD");

        jCurrencyConvert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCurrencyConvert.setText("Convert");
        jCurrencyConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCurrencyConvertActionPerformed(evt);
            }
        });

        jCurrencyClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCurrencyClose.setText("Close");
        jCurrencyClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCurrencyCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jCurrencyConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCurrencyClose)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCurrencyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jCurrencyTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(31, 31, 31))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jCurrencyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jCurrencyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCurrencyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addComponent(jCurrencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCurrencyConvert)
                    .addComponent(jCurrencyClose))
                .addGap(47, 47, 47))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTotalTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTotalTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTotalTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTotalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalTextFieldActionPerformed(evt);
            }
        });

        jTaxTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTaxTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTaxTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTaxTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTaxTextFieldActionPerformed(evt);
            }
        });

        jSubtotalTextField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSubtotalTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jSubtotalTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Subtotal:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Tax:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Total:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTaxTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jSubtotalTextField)
                    .addComponent(jTotalTextField))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSubtotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTaxTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTxtArea.setColumns(20);
        jTxtArea.setRows(5);
        jScrollPane1.setViewportView(jTxtArea);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Receipt", jPanel8);

        jtxtCalDisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCalDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtCalDisplay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jBtn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });

        jBtn3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });

        jBtn4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });

        jBtn5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });

        jBtn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });

        jBtn6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });

        jBtn7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });

        jBtn8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });

        jBtn9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });

        jBtn0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });

        jBtnDecimal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnDecimal.setText(".");
        jBtnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDecimalActionPerformed(evt);
            }
        });

        jBtnOpposite.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnOpposite.setText("±");
        jBtnOpposite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOppositeActionPerformed(evt);
            }
        });

        jBtnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnAdd.setText("+");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        jBtnSubtract.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnSubtract.setText("-");
        jBtnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubtractActionPerformed(evt);
            }
        });

        jBtnMul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnMul.setText("*");
        jBtnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMulActionPerformed(evt);
            }
        });

        jBtnDivide.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnDivide.setText("/");
        jBtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivideActionPerformed(evt);
            }
        });

        jBtnPercent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnPercent.setText("%");
        jBtnPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPercentActionPerformed(evt);
            }
        });

        jBtnClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnClear.setText("C");
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });

        jBtnBackspace.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnBackspace.setText("←");
        jBtnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackspaceActionPerformed(evt);
            }
        });

        jBtnEqualto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnEqualto.setText("=");
        jBtnEqualto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEqualtoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCalDisplay)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnMul, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnOpposite, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jBtnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnEqualto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jtxtCalDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnOpposite, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnMul, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEqualto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Calculator", jPanel9);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jTotalBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTotalBtn.setText("Total");
        jTotalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalBtnActionPerformed(evt);
            }
        });

        jReceiptBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jReceiptBtn.setText("Receipt");
        jReceiptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReceiptBtnActionPerformed(evt);
            }
        });

        jResetbtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jResetbtn.setText("Reset");
        jResetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetbtnActionPerformed(evt);
            }
        });

        jExitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jExitBtn.setText("Exit");
        jExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jTotalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jReceiptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jResetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jExitBtn)
                    .addComponent(jResetbtn)
                    .addComponent(jReceiptBtn)
                    .addComponent(jTotalBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jVegBurgerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVegBurgerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jVegBurgerTextFieldActionPerformed

    private void jChickenBurgerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChickenBurgerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChickenBurgerTextFieldActionPerformed

    private void jVegBurgerCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVegBurgerCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jVegBurgerCheckBoxActionPerformed

    private void jBaconCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBaconCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBaconCheckBoxActionPerformed

    private void jCheckBoxHomeDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHomeDeliveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxHomeDeliveryActionPerformed

    private void jTaxCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTaxCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTaxCheckBoxActionPerformed

    private void jCostOfHomeDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCostOfHomeDeliveryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCostOfHomeDeliveryActionPerformed

    private void jCostOfDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCostOfDrinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCostOfDrinksActionPerformed

    private void jCurrencyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCurrencyTextFieldActionPerformed
        
    }//GEN-LAST:event_jCurrencyTextFieldActionPerformed

    private void jCurrencyConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCurrencyConvertActionPerformed
        double CAD=Double.parseDouble(jCurrencyTextField.getText());
        if(jCurrencyComboBox.getSelectedItem().equals("India")){
            String s=String.format("INR %.2f", CAD*IndianRupee);
            jCurrencyLabel.setText(s);
        }
        if(jCurrencyComboBox.getSelectedItem().equals("Australia")){
            String s=String.format("AUD %.2f", CAD*Aud);
            jCurrencyLabel.setText(s);
        }
        if(jCurrencyComboBox.getSelectedItem().equals("England")){
            String s=String.format("£ %.2f", CAD*BritishPounds);
            jCurrencyLabel.setText(s);
        }
        if(jCurrencyComboBox.getSelectedItem().equals("USA")){
            String s=String.format("$ %.2f", CAD*USD);
            jCurrencyLabel.setText(s);
        }
        if(jCurrencyComboBox.getSelectedItem().equals("Kenya")){
            String s=String.format("KS %.2f", CAD*kenyanShilling);
            jCurrencyLabel.setText(s);
        }
        if(jCurrencyComboBox.getSelectedItem().equals("Nigeria")){
            String s=String.format("N %.2f", CAD*NigerianNaira);
            jCurrencyLabel.setText(s);
        }
        if(jCurrencyComboBox.getSelectedItem().equals("Indonesia")){
            String s=String.format("Idr %.2f", CAD*IndonesianRupiah);
            jCurrencyLabel.setText(s);
        }
        
    }//GEN-LAST:event_jCurrencyConvertActionPerformed

    private void jCurrencyCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCurrencyCloseActionPerformed
        jCurrencyComboBox.setSelectedIndex(0);
        jCurrencyTextField.setText(null);
        jCurrencyLabel.setText(null);
    }//GEN-LAST:event_jCurrencyCloseActionPerformed

    private void jTotalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTotalTextFieldActionPerformed

    private void jTaxTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTaxTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTaxTextFieldActionPerformed

    private void jResetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetbtnActionPerformed
        jtxtCalDisplay.setText(null);
        jCurrencyTextField.setText(null);
        jCurrencyLabel.setText(null);
        jCurrencyComboBox.setSelectedIndex(0);
        jCostOfHomeDelivery.setText(null);
        jCostOfDrinks.setText(null);
        jCostOfMeal.setText(null);
        jSubtotalTextField.setText(null);
        jTotalTextField.setText(null);
        jTaxTextField.setText(null);
        jVegBurgerTextField.setText(null);
        jChickenBurgerTextField.setText(null);
        jBaconTextField.setText(null);
        jVegBurgerCheckBox.setSelected(false);
        jChickenBurgerCheckBox.setSelected(false);
        jBaconCheckBox.setSelected(false);
        jDrinkComboBox.setSelectedIndex(0);
        jTaxCheckBox.setSelected(false);
        jCheckBoxHomeDelivery.setSelected(false);
        jTxtArea.setText(null);
        
        
        
        
        
        
        
    }//GEN-LAST:event_jResetbtnActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        String Enternumber=jtxtCalDisplay.getText()+jBtn2.getText();
       jtxtCalDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jExitBtnActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
        String Enternumber=jtxtCalDisplay.getText()+jBtn7.getText();
       jtxtCalDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed

       String Enternumber=jtxtCalDisplay.getText()+jBtn1.getText();
       jtxtCalDisplay.setText(Enternumber);
       
       
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
        String Enternumber=jtxtCalDisplay.getText()+jBtn3.getText();
       jtxtCalDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
        String Enternumber=jtxtCalDisplay.getText()+jBtn4.getText();
       jtxtCalDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
        String Enternumber=jtxtCalDisplay.getText()+jBtn5.getText();
       jtxtCalDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
        String Enternumber=jtxtCalDisplay.getText()+jBtn6.getText();
       jtxtCalDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
        String Enternumber=jtxtCalDisplay.getText()+jBtn8.getText();
       jtxtCalDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        String Enternumber=jtxtCalDisplay.getText()+jBtn9.getText();
       jtxtCalDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
        String Enternumber=jtxtCalDisplay.getText()+jBtn0.getText();
       jtxtCalDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDecimalActionPerformed
        String Enternumber=jtxtCalDisplay.getText()+jBtnDecimal.getText();
       jtxtCalDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtnDecimalActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        firstnum=Double.parseDouble(jtxtCalDisplay.getText());
        jtxtCalDisplay.setText("");
        Operations="+";
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubtractActionPerformed
        firstnum=Double.parseDouble(jtxtCalDisplay.getText());
        jtxtCalDisplay.setText("");
        Operations="-";
    }//GEN-LAST:event_jBtnSubtractActionPerformed

    private void jBtnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMulActionPerformed
        firstnum=Double.parseDouble(jtxtCalDisplay.getText());
        jtxtCalDisplay.setText("");
        Operations="*";
    }//GEN-LAST:event_jBtnMulActionPerformed

    private void jBtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivideActionPerformed
        firstnum=Double.parseDouble(jtxtCalDisplay.getText());
        jtxtCalDisplay.setText("");
        Operations="/";
    }//GEN-LAST:event_jBtnDivideActionPerformed

    private void jBtnPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPercentActionPerformed
        firstnum=Double.parseDouble(jtxtCalDisplay.getText());
        jtxtCalDisplay.setText("");
        Operations="%";
    }//GEN-LAST:event_jBtnPercentActionPerformed

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        jtxtCalDisplay.setText(null);
    }//GEN-LAST:event_jBtnClearActionPerformed

    private void jBtnEqualtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEqualtoActionPerformed
        secondnum=Double.parseDouble(jtxtCalDisplay.getText());
        if(Operations=="+")
        {
            result=firstnum+secondnum;
            String answer=String.format("%.2f", result);
            jtxtCalDisplay.setText(answer);
        }
        if(Operations=="-")
        {
            result=firstnum-secondnum;
            String answer=String.format("%.2f", result);
            jtxtCalDisplay.setText(answer);
        }
        if(Operations=="/")
        {
            result=firstnum/secondnum;
            String answer=String.format("%.2f", result);
            jtxtCalDisplay.setText(answer);
        }
        if(Operations=="*")
        {
            result=firstnum*secondnum;
            String answer=String.format("%.2f", result);
            jtxtCalDisplay.setText(answer);
        }
        if(Operations=="%")
        {
            result=firstnum%secondnum;
            String answer=String.format("%.2f", result);
            jtxtCalDisplay.setText(answer);
        }
        
    }//GEN-LAST:event_jBtnEqualtoActionPerformed

    private void jBtnOppositeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOppositeActionPerformed
        double ops= Double.parseDouble(jtxtCalDisplay.getText());
        double ops1= ops*(-1);
        String s= String.valueOf(ops1);
        jtxtCalDisplay.setText(s);
    }//GEN-LAST:event_jBtnOppositeActionPerformed

    private void jBtnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackspaceActionPerformed
 
       if(jtxtCalDisplay.getText().length()>0) 
        {
            StringBuilder str = new StringBuilder(jtxtCalDisplay.getText());
            str.deleteCharAt(jtxtCalDisplay.getText().length()-1);
            String backspace = str.toString();
            jtxtCalDisplay.setText(backspace);
        }
       
    }//GEN-LAST:event_jBtnBackspaceActionPerformed

    private void jCheckBoxHomeDeliveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxHomeDeliveryMouseClicked
        double DeliveryCost=3.39;
        if(jCheckBoxHomeDelivery.isSelected())
        {
            String iDeliveryCost=String.format("%.2f",DeliveryCost);
            jCostOfHomeDelivery.setText(iDeliveryCost);
        }
        else{
            jCostOfHomeDelivery.setText(null);
        
        }
        
    }//GEN-LAST:event_jCheckBoxHomeDeliveryMouseClicked

    private void jDrinkComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDrinkComboBoxActionPerformed
        double Apple_Juice=2.99;
        double Orange_Juice=3.99;
        double Tea1=1.99;
        double hotCoffee=2.99;
        double coldCoffee=3.75;
        double coke1=2.75;
        double sprite1=3.99;
        
        if(jDrinkComboBox.getSelectedItem().equals("Select a drink..."))
        {
            jCostOfDrinks.setText(null);
        }
        if(jDrinkComboBox.getSelectedItem().equals("Apple Juice"))
        {
            String d=String.format("%.2f", Apple_Juice);
            jCostOfDrinks.setText(d);
        }
        if(jDrinkComboBox.getSelectedItem().equals("Orange Juice"))
        {
            String d=String.format("%.2f", Orange_Juice);
            jCostOfDrinks.setText(d);
        }
        if(jDrinkComboBox.getSelectedItem().equals("Tea"))
        {
            String d=String.format("%.2f", Tea1);
            jCostOfDrinks.setText(d);
        }
        if(jDrinkComboBox.getSelectedItem().equals("Hot Coffee"))
        {
            String d=String.format("%.2f", hotCoffee);
            jCostOfDrinks.setText(d);
        }
        if(jDrinkComboBox.getSelectedItem().equals("Cold Coffee"))
        {
            String d=String.format("%.2f", coldCoffee);
            jCostOfDrinks.setText(d);
        }
         if(jDrinkComboBox.getSelectedItem().equals("Coke"))
        {
            String d=String.format("%.2f", coke1);
            jCostOfDrinks.setText(d);
        }
         if(jDrinkComboBox.getSelectedItem().equals("Sprite"))
        {
            String d=String.format("%.2f", sprite1);
            jCostOfDrinks.setText(d);
        } 
       
    }//GEN-LAST:event_jDrinkComboBoxActionPerformed

    private void jVegBurgerCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVegBurgerCheckBoxMouseClicked
        double costOfMealtxtfld=Double.parseDouble(jCostOfMeal.getText());
        double Burgertxtfld=Double.parseDouble(jVegBurgerTextField.getText());
        double BurgerCost=5.99;
        
        if(jVegBurgerCheckBox.isSelected())
        {
            
            double CostOfMealDisplay=(BurgerCost*Burgertxtfld)+costOfMealtxtfld;
            String s=String.format("%.2f", CostOfMealDisplay);
            jCostOfMeal.setText(s);
        }
    }//GEN-LAST:event_jVegBurgerCheckBoxMouseClicked

    private void jChickenBurgerCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChickenBurgerCheckBoxMouseClicked
        double costOfMealtxtfld=Double.parseDouble(jCostOfMeal.getText());
        double Burgertxtfld=Double.parseDouble(jChickenBurgerTextField.getText());
        double BurgerCost=7.99;
        
        if(jChickenBurgerCheckBox.isSelected())
        {
            
            double CostOfMealDisplay=(BurgerCost*Burgertxtfld)+costOfMealtxtfld;
            String s=String.format("%.2f", CostOfMealDisplay);
            jCostOfMeal.setText(s);
        }
    }//GEN-LAST:event_jChickenBurgerCheckBoxMouseClicked

    private void jBaconCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBaconCheckBoxMouseClicked
        double costOfMealtxtfld=Double.parseDouble(jCostOfMeal.getText());
        double Burgertxtfld=Double.parseDouble(jBaconTextField.getText());
        double BurgerCost=8.99;
        
        if(jBaconCheckBox.isSelected())
        {
            
            double CostOfMealDisplay=(BurgerCost*Burgertxtfld)+costOfMealtxtfld;
            String s=String.format("%.2f", CostOfMealDisplay);
            jCostOfMeal.setText(s);
        }
    }//GEN-LAST:event_jBaconCheckBoxMouseClicked

    private void jTaxCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTaxCheckBoxMouseClicked
        double costofMeal=Double.parseDouble(jCostOfMeal.getText());
        double costofDelivery=Double.parseDouble(jCostOfHomeDelivery.getText());
        double costofDrinks=Double.parseDouble(jCostOfDrinks.getText());
            
        double d=(costofMeal+ costofDelivery+costofDrinks)/100;
        String s=String.format("%.2f", d);
        jTaxTextField.setText(s);
        
    }//GEN-LAST:event_jTaxCheckBoxMouseClicked

    private void jTotalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalBtnActionPerformed
        double costofMeal=Double.parseDouble(jCostOfMeal.getText());
        double costofDelivery=Double.parseDouble(jCostOfHomeDelivery.getText());
        double costofDrinks=Double.parseDouble(jCostOfDrinks.getText());
        
        double subtotal= costofMeal + costofDelivery+costofDrinks;
        String s=String.format("CAD %.2f", subtotal);
        jSubtotalTextField.setText(s);
        
        double tax=Double.parseDouble(jTaxTextField.getText());
        double total=costofMeal + costofDelivery+costofDrinks+tax;
        String u=String.format("CAD %.2f", tax);
        jTaxTextField.setText(u);
        String t=String.format("CAD %.2f", total);
        jTotalTextField.setText(t);
        
        
    }//GEN-LAST:event_jTotalBtnActionPerformed

    private void jReceiptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReceiptBtnActionPerformed
        double Qty1= Double.parseDouble(jVegBurgerTextField.getText());
        double Qty2= Double.parseDouble(jChickenBurgerTextField.getText());
        double Qty3= Double.parseDouble(jBaconTextField.getText());
        double Qty4=Double.parseDouble(jCostOfHomeDelivery.getText());
        double Qty5=Double.parseDouble(jCostOfDrinks.getText());
        double Qty6=Double.parseDouble(jCostOfMeal.getText());
        /*double Qty7=Double.parseDouble(jSubtotalTextField.getText());
        double Qty8=Double.parseDouble(jTaxTextField.getText());
        double Qty9=Double.parseDouble(jTotalTextField.getText());
        */
        jTxtArea.append("Restaurant Management Systems:\n\n" + "Veg. Burger:\t\t\t"
        + Qty1 + "\nChicken Burger:\t\t" +
        Qty2+ "\nBacon Chicken Burger:\t\t"
        +Qty3 +"\nCost of Meal:\t\t\t"+Qty6+"\nCost of Drinks:\t\t\t"+Qty5+ 
               "\nCost of Home Delivery:\t\t"+Qty4+"\n\nThanks for using the application");
    }//GEN-LAST:event_jReceiptBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelMenuSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelMenuSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelMenuSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelMenuSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelMenuSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jBaconCheckBox;
    private javax.swing.JTextField jBaconTextField;
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnBackspace;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnDecimal;
    private javax.swing.JButton jBtnDivide;
    private javax.swing.JButton jBtnEqualto;
    private javax.swing.JButton jBtnMul;
    private javax.swing.JButton jBtnOpposite;
    private javax.swing.JButton jBtnPercent;
    private javax.swing.JButton jBtnSubtract;
    private javax.swing.JCheckBox jCheckBoxHomeDelivery;
    private javax.swing.JCheckBox jChickenBurgerCheckBox;
    private javax.swing.JTextField jChickenBurgerTextField;
    private javax.swing.JTextField jCostOfDrinks;
    private javax.swing.JTextField jCostOfHomeDelivery;
    private javax.swing.JTextField jCostOfMeal;
    private javax.swing.JButton jCurrencyClose;
    private javax.swing.JComboBox<String> jCurrencyComboBox;
    private javax.swing.JButton jCurrencyConvert;
    private javax.swing.JLabel jCurrencyLabel;
    private javax.swing.JTextField jCurrencyTextField;
    private javax.swing.JComboBox<String> jDrinkComboBox;
    private javax.swing.JButton jExitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jReceiptBtn;
    private javax.swing.JButton jResetbtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSubtotalTextField;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox jTaxCheckBox;
    private javax.swing.JTextField jTaxTextField;
    private javax.swing.JButton jTotalBtn;
    private javax.swing.JTextField jTotalTextField;
    private javax.swing.JTextArea jTxtArea;
    private javax.swing.JCheckBox jVegBurgerCheckBox;
    private javax.swing.JTextField jVegBurgerTextField;
    private javax.swing.JTextField jtxtCalDisplay;
    // End of variables declaration//GEN-END:variables
}
